### ISSUE TITLE
Customize window layout

### ISSUE THREAD

**Issue by thanniaB** [meetfranz/franz#156]
Make a way to be able to reposition sidebar or resize  

### Expected Behavior

If it's possible, either a way to resize the conversation sidebar inside the services OR a switchable setting in which you can choose to have the services in a sidebar or above like the old version did.
### Current Behavior

Everything is side by side (service sidebar > conversations > conversation) and makes me have a very long window, it's also weird to read.

### Screenshots (if appropriate):
<img width="1163" alt="screenshot at oct 27 11-14-24" src="https://user-images.githubusercontent.com/4682286/32118854-14da7a30-bb08-11e7-9272-a9076ef9276a.png">

### Steps to Reproduce (for bugs)

1.
2.
3.
4.

### Context

I just updated Franz and all changes are weird I guess, I was used to having the services above and now they're on a sidebar, which looked neat at first but makes me have a very long window, because now the layout is service > conversation list > conversation, in some services like slack it's okay but on others like whatsapp and telegram the conversation list is too wide. I suggest the option of having a setting in which you can put the services either above or in the sidebar so that way anybody can have the way they like it better ^^

### Your Environment

* Franz Version used: 5
* Operating System and version: OSX El Capitan

**Comment by alecive** [comment]
@thanniaB the size of the conversation sidebar is not constant and it depends on the application. E.g. whatsapp would have it bigger than slack for example. So there is nothing `franz` could (or should) do for it!

**Comment by Shadester** [comment]
I would love to have the option to have it in tabs like in the old version.

**Comment by adlk** [comment]
As @alecive already statet correctly we shouldn't modify the service itself too much.

_Ad an alternative tab bar layout:_ this is definitely something I have planned for a future release. But as you can imagine it hasn't the highest priority right now.

**Comment by cpazaras** [comment]
Just a +1 for a setting to restore the old (top) tab bar layout from me as well - I also found it much more convenient on the top than on the left.
(To avoid any misunderstandings due to previous comments - I am of course referring to Franz's services tab, **not** the native tabs of individual services such as e.g. Whatsapp - it wouldn't be a third-party application's responsibility to alter those).

**Comment by RWOverdijk** [comment]
A practical example is me being part of 12 slack communities. Good luck figuring out which slack icon is which :D haha

**Comment by dkhaziev** [comment]
I have two displays and I places the Franz window at right half of right display.
In my case I want place the Tab on top of the window or on the right side. Left side is unusable for me.

And for case of Tab on top, I want to start compose icons from the right.

My desktop on right monitor for example:
![ss06](https://user-images.githubusercontent.com/27686102/33211085-f1ada51e-d12d-11e7-9509-ef2053a19ed0.jpg)

**Comment by philippkahr** [comment]
+1 and I would love to disable the bar completely. I only use two messaging systems like WhatsApp and Facebook, and I rarely am messaged on facebook, so it would be nice to win the space by not showing bar.

**Comment by danionita** [comment]
So you made a debatable, unnecessary design decision many people disliked, without giving users a choice.  Then, instead of reverting or making it a setting, you label the issue as a low-priority feature request despite many complaints... Love the tool but dislike this behavior. It sounds like Google or Microsoft "developing for the majority". Considering to stop my recurrent donation tbh.

**Comment by adamprescott** [comment]
I also prefer the tabs along the top, I played about with the CSS in the inspector tools and got this result
![capture](https://user-images.githubusercontent.com/321588/36454990-1db89558-1696-11e8-9e86-caa05914689d.PNG)
The drag and drop ordering isn't working as it should but you get the basic idea.
```css
.app { /* main.css:6130 */
    display: flex;
    flex-direction: column;
}
.sidebar { /* main.css:6152 */
    display: flex;
    flex-direction: row;
    align-items: center;
    height: 50px;
    background: #f7f7f9;
    box-shadow: 1px 0 10px rgba(0, 0, 0, 0.08);
    z-index: 200;
    text-align: center;
    color: #373a3c;
}
.tabs { /* main.css:6229 */
    display: flex;
    flex-direction: row;
    flex-shrink: 1;
}
.tab-item { /* main.css:6238 */
    display: flex;
    justify-content: center;
    align-items: center;
    position: relative;
    width: 68px;
    /* height: 65px; */
    min-height: 50px;
    transition: background 0.5s;
}
.tab-item.is-active { /* main.css:6248 */
    border-bottom: 4px solid #3498db;
    background: #cce5f6;
}
```
